max_batch: 1
stages:
  - name: prompt_encoder
    default_sampling_params:
      sat_threshold: 0.02
  - name: mimir_lcm
    default_sampling_params:
      inference_timesteps: 40
      guidance_scale: 1.5
      guidance_rescale: 0.7
      initial_noise_scale: 0.6
      epsilon_scaling: 1.00045
      eos_threshold: 0.9
      stop_on_repetition_cosine_threshold: 0.9
      seed: 42
  - name: text_decoder
    default_sampling_params: {}